config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  get 'static/home'
  get 'static/about'
  get 'static/contact'

  resources :cars
  resources :customers
  resources :invoices
  resources :orders
  resources :stops
  resources :users

  get 'generate_invoice/show'
  get 'generate_contract/show'

  get 'login' => 'user_sessions#new', as: :login
  post 'login' => 'user_sessions#create'
  post 'logout' => 'user_sessions#destroy', as: :logout

  root to: 'static#home'
end

app/models/stop.rb
# == Schema Information
#
# Table name: stops
#
#  id         :bigint           not null, primary key
#  city       :string
#  country    :string
#  label      :string           not null
#  number     :string
#  sequence   :integer
#  street     :string
#  type       :string
#  way_back   :boolean          default(FALSE)
#  zip_code   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  order_id   :bigint           not null
#
# Indexes
#
#  index_stops_on_order_id  (order_id)
#
# Foreign Keys
#
#  fk_rails_...  (order_id => orders.id)
#
class Stop < ApplicationRecord
  belongs_to :order

  before_create :set_sequence

  scope :forward, -> { where(way_back: false) }
  scope :back, -> { where(way_back: true) }

  def text
    "#{label}, #{street} #{number}, #{zip_code} #{city}, #{country}"
  end

  def self.inherited(child)
    child.instance_eval do
      def model_name
        Stop.model_name
      end
    end
    super
  end

  private

  def set_sequence
    last = self.order.stops.order(:sequence).last
    seq = last.present? ? last.sequence + 1 : 1
    self.sequence = seq
  end
end

app/models/stop/loading.rb
# == Schema Information
#
# Table name: stops
#
#  id         :bigint           not null, primary key
#  city       :string
#  country    :string
#  label      :string           not null
#  number     :string
#  sequence   :integer
#  street     :string
#  type       :string
#  way_back   :boolean          default(FALSE)
#  zip_code   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  order_id   :bigint           not null
#
# Indexes
#
#  index_stops_on_order_id  (order_id)
#
# Foreign Keys
#
#  fk_rails_...  (order_id => orders.id)
#
class Stop::Loading < Stop
end

app/models/stop/unloading.rb
# == Schema Information
#
# Table name: stops
#
#  id         :bigint           not null, primary key
#  city       :string
#  country    :string
#  label      :string           not null
#  number     :string
#  sequence   :integer
#  street     :string
#  type       :string
#  way_back   :boolean          default(FALSE)
#  zip_code   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  order_id   :bigint           not null
#
# Indexes
#
#  index_stops_on_order_id  (order_id)
#
# Foreign Keys
#
#  fk_rails_...  (order_id => orders.id)
#
class Stop::Unloading < Stop
end

app/controllers/stops_controller.rb
class StopsController < ApplicationController
  before_action :set_stop, only: %i[ show edit update destroy ]

  # GET /stops or /stops.json
  def index
    @stops = Stop.all
  end

  # GET /stops/1 or /stops/1.json
  def show
  end

  # GET /stops/new
  def new
    @stop = Stop.new
  end

  # GET /stops/1/edit
  def edit
  end

  # POST /stops or /stops.json
  def create
    @stop = params[:type].constantize.new(stop_params)

    respond_to do |format|
      if @stop.save
        format.html { redirect_to edit_order_path @stop.order, notice: "Stop was successfully created." }
        format.json { render :show, status: :created, location: @stop }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stops/1 or /stops/1.json
  def update
    respond_to do |format|
      if @stop.update(stop_params)
        format.html { redirect_to edit_order_path(@order), notice: "Stop was successfully updated." }
        format.json { render :show, status: :ok, location: @stop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stops/1 or /stops/1.json
  def destroy
    @stop.destroy
    respond_to do |format|
      format.html { redirect_to edit_order_path(@order), notice: "Stop was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stop
      @stop = Stop.find(params[:id])
      @order = @stop.order
    end

    # Only allow a list of trusted parameters through.
    def stop_params
      params.require(:stop).permit(:order_id, :label, :street, :number, :zip_code, :city, :country, :way_back)
    end
end

app/helpers/stops_helper.rb
module StopsHelper
end

app/views/stops/_form.html.erb
<%= form_with(model: stop, local: true) do |form| %>
  <% if stop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stop.errors.count, "error") %> prohibited this stop from being saved:</h2>

      <ul>
        <% stop.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :label %>
    <%= form.text_field :label %>
  </div>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :zip_code %>
    <%= form.text_field :zip_code %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :way_back %>
    <%= form.check_box :way_back %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stops/edit.html.erb
<h1>Editing Stop</h1>

<%= render 'form', stop: @stop %>

<%= link_to 'Show', @stop %> |
<%= link_to 'Back', stops_path %>

app/views/stops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stops</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Label</th>
      <th>Street</th>
      <th>Number</th>
      <th>Zip code</th>
      <th>City</th>
      <th>Country</th>
      <th>Way back</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stops.each do |stop| %>
      <tr>
        <td><%= stop.type %></td>
        <td><%= stop.label %></td>
        <td><%= stop.street %></td>
        <td><%= stop.number %></td>
        <td><%= stop.zip_code %></td>
        <td><%= stop.city %></td>
        <td><%= stop.country %></td>
        <td><%= stop.way_back %></td>
        <td><%= link_to 'Show', stop %></td>
        <td><%= link_to 'Edit', edit_stop_path(stop) %></td>
        <td><%= link_to 'Destroy', stop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stop', new_stop_path %>

app/views/stops/new.html.erb
<h1>New Stop</h1>

<%= render 'form', stop: @stop %>

<%= link_to 'Back', stops_path %>

app/views/stops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @stop.type %>
</p>

<p>
  <strong>Label:</strong>
  <%= @stop.label %>
</p>

<p>
  <strong>Street:</strong>
  <%= @stop.street %>
</p>

<p>
  <strong>Number:</strong>
  <%= @stop.number %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @stop.zip_code %>
</p>

<p>
  <strong>City:</strong>
  <%= @stop.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @stop.country %>
</p>

<p>
  <strong>Way back:</strong>
  <%= @stop.way_back %>
</p>

<%= link_to 'Edit', edit_stop_path(@stop) %> |
<%= link_to 'Back', stops_path %>