config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  get 'static/home'
  get 'static/about'
  get 'static/contact'

  resources :cars
  resources :customers
  resources :invoices
  resources :orders
  resources :stops
  resources :users

  get 'generate_invoice/show'
  get 'generate_contract/show'

  get 'login' => 'user_sessions#new', as: :login
  post 'login' => 'user_sessions#create'
  post 'logout' => 'user_sessions#destroy', as: :logout

  root to: 'static#home'
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id               :bigint           not null, primary key
#  currency         :text
#  datum            :date
#  distance         :decimal(10, 2)
#  finished         :boolean
#  fix_price        :boolean
#  label            :text
#  load_capacity    :decimal(10, 3)
#  load_description :text
#  load_type        :text
#  load_volume      :decimal(10, 3)
#  price            :decimal(10, 3)
#  price_per_km     :decimal(10, 3)
#  vat_percentage   :decimal(10, 3)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  car_id           :integer
#  customer_id      :bigint           not null
#  destination_id   :integer
#  origin_id        :integer
#  user_id          :bigint           not null
#
# Indexes
#
#  index_orders_on_customer_id  (customer_id)
#  index_orders_on_user_id      (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (customer_id => customers.id)
#  fk_rails_...  (user_id => users.id)
#
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :user
  belongs_to :origin, foreign_key: :origin_id, class_name: 'Customer'
  belongs_to :destination, foreign_key: :destination_id, class_name: 'Customer'
  has_many :invoices
  belongs_to :car
  has_many :stops
  has_many :stop_loadings, class_name: 'Stop::Loading'
  has_many :stop_unloadings, class_name: 'Stop::Unloading'

  scope :finished, -> { where(finished: true) }
  scope :active, -> { where(finished: false) }

  after_initialize :default_values

  def full_price
    if fix_price?
      price || 0.0
    else
      (price_per_km || 0.0) * (distance || 0.0)
    end
  end

  def vat_price
    full_price * (vat_percentage / 100.0)
  end

  def price_with_vat
    full_price + vat_price
  end

  private

  def default_values
    self.vat_percentage ||= 21.0
    self.finished ||= false
    self.currency ||= 'Kč'
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    scope = params[:scope] || 'active'
    @orders = Order.includes(:origin, :destination, :customer, :user, :invoices).send(scope).order(:datum).all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
    @stop = @order.stops.new
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.user = current_user

    respond_to do |format|
      if @order.save
        format.html { redirect_to edit_order_path @order, notice: 'Zakázka byla uložena.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_path(scope: 'active'), notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:datum, :load_type, :load_description, :load_capacity, :load_volume,
                                    :origin_id, :destination_id, :distance, :finished, :fix_price, :price_per_km,
                                    :price, :customer_id, :currency, :label, :vat_percentage, :car_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def stop_line_style(stop)
    return 'loading' if stop.class == Stop::Loading && !stop.way_back
    return 'back_loading' if stop.class == Stop::Loading && stop.way_back
    return 'unloading' if stop.class == Stop::Unloading && !stop.way_back
    return 'back_unloading' if stop.class == Stop::Unloading && stop.way_back
    ''
  end

  def crossed?(order)
    order.finished ? 'crossed' : ''
  end
end

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-6">
      <%= render 'form/date_select', form: form, column: :datum %>

      <%= render 'form/text_field', form: form, column: :label %>

      <%= render 'form/select', form: form, column: :customer_id, options_var: options_from_collection_for_select(Customer.all, 'id', 'name', @order.customer_id) %>

      <%= render 'form/select', form: form, column: :origin_id, options_var: options_from_collection_for_select(Customer.all, 'id', 'name', @order.origin_id) %>

      <%= render 'form/select', form: form, column: :destination_id, options_var: options_from_collection_for_select(Customer.all, 'id', 'name', @order.destination_id) %>
      <fieldset style="border: black">
        <legend><%= t('activerecord.attributes.order.fix_price') %></legend>
        <%= render 'form/check_box', form: form, column: :fix_price %>

        <%= render 'form/text_field', form: form, column: :price %>
      </fieldset>
      <br/>
      <fieldset>
        <legend>Cena spočtená ze vzdálenosti a ceny za kilometr</legend>
        <%= render 'form/text_field', form: form, column: :distance %>

        <%= render 'form/text_field', form: form, column: :price_per_km %>
      </fieldset>
    </div>
    <div class="col-6">
      <%= render 'form/number_field', form: form, column: :vat_percentage %>

      <%= render 'form/select', form: form, column: :currency, options_var: options_for_select(%w[Kč €], @order.currency) %>

      <%= render 'form/text_field', form: form, column: :load_type %>

      <%= render 'form/text_field', form: form, column: :load_description %>

      <%= render 'form/text_field', form: form, column: :load_capacity %>

      <%= render 'form/text_field', form: form, column: :load_volume %>

      <%= render 'form/select', form: form, column: :car_id, options_var: options_from_collection_for_select(Car.active.all, 'id', 'name', @order.car_id) %>
      <br/>
      <br/>
      <%= render 'form/check_box', form: form, column: :finished %>
    </div>
  </div>

  <div class="actions">
    <%= form.button 'Uložit' %>
  </div>
<% end %>
<% if @order.id.present? %>
  <hr/>
  <div class="row">
    <div class="col-5">
      <%= form_with(model: @stop, local: true) do |form| %>
        <% if @stop.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@stop.errors.count, "error") %> prohibited this stop from being saved:</h2>

            <ul>
              <% @stop.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <%= form.hidden_field :order_id, value: @order.id %>

        <%= render 'form/text_field', form: form, column: :label %>

        <%= render 'form/text_field', form: form, column: :street %>

        <%= render 'form/text_field', form: form, column: :number %>

        <%= render 'form/text_field', form: form, column: :zip_code %>

        <%= render 'form/text_field', form: form, column: :city %>

        <%= render 'form/text_field', form: form, column: :country %>

        <%= render 'form/check_box', form: form, column: :way_back %>

        <div class="actions">
          <%= form.button 'Nakládka', value: 'Stop::Loading', name: 'type', class: 'button', type: 'submit' %>
          <%= form.button 'Vykládka', value: 'Stop::Unloading', name: 'type', class: 'button', type: 'submit' %>
        </div>
      <% end %>

    </div>
    <div class="col-7">
      <table class="table-sm">
        <tr>
          <th><%= t('activerecord.attributes.stop.sequence') %></th>
          <th><%= t('activerecord.attributes.customer.address') %></th>
          <th></th>
          <th></th>
        </tr>
        <% @order.stops.each do |stop| %>
          <% next if stop.id.blank? %>
          <tr>
            <td class="<%= stop_line_style(stop) %>">
              <%= stop.sequence %>.
            </td>
            <td class="<%= stop_line_style(stop) %>">
              <%= stop.text %>
            </td>
            <td class="<%= stop_line_style(stop) %>">
              <%= stop.way_back ? 'Zpáteční' : '' %>
            </td>
            <td class="<%= stop_line_style(stop) %>">
              <%= link_to fa_icon('edit 2x'), edit_stop_path(stop) %>
              <%= link_to fa_icon('trash 2x'), stop_path(stop), method: :delete, data: { confirm: 'Opravdu odstranit?' } %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editace <%= @order.label %></h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t 'zakazka.' + params[:scope].to_s %><%= Order.model_name.human(count: 2) %></h1>

<table class="niceTable">
  <thead>
    <tr>
      <th><%= t 'activerecord.attributes.order.datum' %></th>
      <th><%= t 'activerecord.attributes.order.label' %></th>
      <th><%= t 'activerecord.attributes.order.origin_id' %></th>
      <th><%= t 'activerecord.attributes.order.destination_id' %></th>
      <th><%= t 'activerecord.attributes.order.full_price' %></th>
      <th colspan="3"><%= link_to 'Nová zakázka', new_order_path %></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= format_date order.datum %></td>
        <td><%= order.label %></td>
        <td>
          <%= order.origin.name %>
          <p style="margin-top: 0"><%= order.origin.city %></p>
        </td>
        <td>
          <%= order.destination.name %>
          <p style="margin-top: 0"><%= order.destination.city %></p>
        </td>
        <td><%= format_currency order.full_price, order.currency %></td>
        <td>
          <% unless order.finished? %>
            <%= button_to order_path(order.id),
                            params: {:order => { :id => order.id, :finished => true }},
                            method: :put, data: { confirm: "Opravdu označit zakázku jako dokončenou?" } do %>
              <%= fa_icon('check-square 2x', text: "Dokonči", left: true).html_safe %>
            <% end %>
          <% end %>
        </td>
        <td>
          <% if order.invoices.present? %>
            <% order.invoices.each do |inv| %>
              <%= link_to inv.reference_number, inv %>
            <% end %>
          <% else %>
            <%= link_to fa_icon('file-alt 2x', text: "Vytvoř fakturu", left: true), controller: :invoices, action: :new, order_id: order.id %>
          <% end %>
        </td>
        <td>
          <%= link_to fa_icon('eye 2x'), order %>&nbsp;
          <%= link_to fa_icon('edit 2x'), edit_order_path(order) %>&nbsp;
          <%= link_to fa_icon('trash 2x'), order, method: :delete, data: { confirm: 'Opravdu smazat?' } if order.invoices.blank? %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/new.html.erb
<h1>Nová zakázka</h1>

<%= render 'form', order: @order %>

<%= link_to 'Přehled zakázek', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<div class="grid-container">
  <div class="leftup">
    <p style="font-size: large">
      <strong><%= t 'activerecord.attributes.order.label' %>:</strong>
      <%= @order.label %>
    </p>

    <p>
      <strong><%= t 'activerecord.attributes.order.datum' %>:</strong>
      <%= format_date @order.datum %>
    </p>

    <p>
      <strong><%= t 'activerecord.attributes.order.load_type' %>:</strong>
      <%= @order.load_type %>
    </p>
  </div>
  <div class="rightup">
    <p>
      <strong><%= t 'activerecord.attributes.order.origin_id' %>:</strong>
      <%= @order.origin.name %>
    </p>

    <p>
      <strong><%= t 'activerecord.attributes.order.destination_id' %>:</strong>
      <%= @order.destination.name %>
    </p>

    <p>
      <strong><%= t 'activerecord.attributes.order.customer_id' %>:</strong>
      <%= @order.customer.name %>
    </p>
  </div>
  <div class="leftmiddle">
    <p>
      <strong><%= t 'activerecord.attributes.order.load_description' %>:</strong>
      <%= @order.load_description %>
    </p>

    <p>
      <strong><%= t 'activerecord.attributes.order.load_capacity' %>:</strong>
      <%= @order.load_capacity %>
    </p>

    <p>
      <strong><%= t 'activerecord.attributes.order.load_volume' %>:</strong>
      <%= @order.load_volume %>
    </p>
  </div>
  <div class="rightmiddle">
    <p>
      <strong><%= t 'activerecord.attributes.order.finished' %>:</strong>
      <%= ano_ne @order.finished %>
    </p>

    <p>
      <strong><%= t 'activerecord.attributes.order.user_id' %>:</strong>
      <%= @order.user.name %>
    </p>

    <p>
      <strong><%= t 'activerecord.attributes.order.currency' %>:</strong>
      <%= @order.currency %>
    </p>

    <p>
      <strong><%= t 'activerecord.attributes.order.vat_percentage' %>:</strong>
      <%= format_currency @order.vat_percentage, '%' %>
    </p>
  </div>
  <div class="leftdown">
    <p>
      <strong><%= t 'activerecord.attributes.order.fix_price' %>:</strong>
      <%= ano_ne @order.fix_price %>
    </p>

    <p>
      <strong><%= t 'activerecord.attributes.order.distance' %>:</strong>
      <%= format_currency @order.distance, 'km' %>
    </p>

    <p>
      <strong><%= t 'activerecord.attributes.order.price_per_km' %>:</strong>
      <%= format_currency @order.price_per_km, @order.currency %>
    </p>

    <p>
      <strong><%= t 'activerecord.attributes.order.price' %>:</strong>
      <%= format_currency @order.price, @order.currency %>
    </p>

    <p>
      <strong><%= t 'activerecord.attributes.order.full_price' %>:</strong>
      <%= format_currency @order.full_price, @order.currency %>
    </p>

    <p>
      <strong><%= t 'activerecord.attributes.order.car_id' %>:</strong>
      <%= link_to @order.car.name, @order.car %>
    </p>
  </div>
  <div class="rightdown">
    <br/><br/>
    <%= link_to fa_icon('edit 2x'), edit_order_path(@order) %>
    <br/>
    <%= link_to fa_icon('list 2x', text: "Přehled zakázek", left: true), orders_path %>
    <br/>
    <%= link_to fa_icon('file-alt 2x', text: "Vytvoř fakturu", left: true), controller: :invoices, action: :new, order_id: @order.id %>
    <br/>
    <%= link_to fa_icon('file-pdf 2x', text: "Vytvoř smlouvu PDF", left: true), generate_contract_show_path(order_id: @order.id, format: :pdf), target: :blank %>
  </div>
</div>
<br/>
<br/>
<br/>
<br/>
<table class="table-sm">
  <tr>
    <th><%= t('activerecord.attributes.stop.sequence') %></th>
    <th><%= t('activerecord.attributes.customer.address') %></th>
    <th></th>
    <th></th>
  </tr>
  <% @order.stops.each do |stop| %>
    <% next if stop.id.blank? %>
    <tr>
      <td class="<%= stop_line_style(stop) %>">
        <%= stop.sequence %>.
      </td>
      <td class="<%= stop_line_style(stop) %>">
        <%= stop.text %>
      </td>
      <td class="<%= stop_line_style(stop) %>">
        <%= stop.way_back ? 'Zpáteční' : '' %>
      </td>
      <td class="<%= stop_line_style(stop) %>">
        <%= link_to fa_icon('edit 2x'), edit_stop_path(stop) %>
        <%= link_to fa_icon('trash 2x'), stop_path(stop), method: :delete, data: { confirm: 'Opravdu odstranit?' } %>
      </td>
    </tr>
  <% end %>
</table>