config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  get 'static/home'
  get 'static/about'
  get 'static/contact'

  resources :cars
  resources :customers
  resources :invoices
  resources :orders
  resources :stops
  resources :users

  get 'generate_invoice/show'
  get 'generate_contract/show'

  get 'login' => 'user_sessions#new', as: :login
  post 'login' => 'user_sessions#create'
  post 'logout' => 'user_sessions#destroy', as: :logout

  root to: 'static#home'
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_examples.html.erb
<!-- Simple Post -->
<section class="simple-post">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="down-content">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="simple-post">
  <div class="container-fluid">

    <div class="row">
      <div class="col-md-6">

      </div>
      <div class="col-md-6">

      </div>
    </div>

  </div>
</section>

<section class="simple-post">
  <div class="container-fluid">

    <div class="row">
      <div class="col-lg-4">
        <h2>First Column</h2>
        <p>Aliquam sit amet gravida tellus. Phasellus id erat nec mi ullamcorper viverra. Quisque vitae pharetra sem. Maecenas sit amet velit ultrices, malesuada quam id, porta nisl.</p>
        <br>

      </div>
      <div class="col-lg-4">
        <h2>Second Column</h2>
        <p>Donec et massa at dolor condimentum ornare nec non lorem. Maecenas non egestas metus, sed ultricies lectus. Aliquam sit amet gravida tellus. Phasellus id erat nec mi ullamcorper viverra.</p>
        <br>

      </div>
      <div class="col-lg-4">
        <h2>Third Column</h2>
        <p>Quisque sodales vestibulum arcu porttitor finibus. Phasellus dictum nisl id augue ornare, vel interdum nibh mollis. Aliquam sit amet gravida tellus.</p>

      </div>
    </div>

  </div>
</section>

<!-- Contact Form -->
<section class="contact-form">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6">
        <form id="contact" action="" method="post">
          <div class="row">
            <div class="col-md-12">
              <fieldset>
                <input name="name" type="text" class="form-control" id="name" placeholder="Your name..." required="">
              </fieldset>
            </div>
            <div class="col-md-12">
              <fieldset>
                <input name="email" type="text" class="form-control" id="email" placeholder="Your email..." required="">
              </fieldset>
            </div>
            <div class="col-md-12">
              <fieldset>
                <textarea name="message" rows="6" class="form-control" id="message" placeholder="Your message..." required=""></textarea>
              </fieldset>
            </div>
            <div class="col-md-12">
              <fieldset>
                <button type="submit" id="form-submit" class="button">Send Message</button>
              </fieldset>
            </div>
          </div>
        </form>
      </div>
      <div class="col-md-6">
        <div id="map">
          <!-- How to change your own map point
                 1. Go to Google Maps
                 2. Click on your location point
                 3. Click "Share" and choose "Embed map" tab
                 4. Copy only URL and paste it within the src="" field below
          -->

          <!--                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1197183.8373802372!2d-1.9415093691103689!3d6.781986417238027!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xfdb96f349e85efd%3A0xb8d1e0b88af1f0f5!2sKumasi+Central+Market!5e0!3m2!1sen!2sth!4v1532967884907" width="100%" height="420px" frameborder="0" style="border:0" allowfullscreen></iframe>-->
        </div>
      </div>
    </div>
  </div>
</section>

<form>
  <div class="form-group row">
    <label for="text" class="col-4 col-form-label">Text Field</label>
    <div class="col-8">
      <div class="input-group">
        <div class="input-group-prepend">
          <div class="input-group-text">
            <i class="fa fa-address-card"></i>
          </div>
        </div>
        <input id="text" name="text" type="text" class="form-control">
      </div>
    </div>
  </div>
  <div class="form-group row">
    <label for="text1" class="col-4 col-form-label">Text Field</label>
    <div class="col-8">
      <input id="text1" name="text1" type="text" class="form-control">
    </div>
  </div>
  <div class="form-group row">
    <label for="select" class="col-4 col-form-label">Select</label>
    <div class="col-8">
      <select id="select" name="select" class="custom-select">
        <option value="rabbit">Rabbit</option>
        <option value="duck">Duck</option>
        <option value="fish">Fish</option>
      </select>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-4">Checkboxes</label>
    <div class="col-8">
      <div class="custom-control custom-checkbox custom-control-inline">
        <input name="checkbox" id="checkbox_0" type="checkbox" checked="checked" class="custom-control-input" value="rabbit">
        <label for="checkbox_0" class="custom-control-label">Rabbit</label>
      </div>
      <div class="custom-control custom-checkbox custom-control-inline">
        <input name="checkbox" id="checkbox_1" type="checkbox" class="custom-control-input" value="duck">
        <label for="checkbox_1" class="custom-control-label">Duck</label>
      </div>
      <div class="custom-control custom-checkbox custom-control-inline">
        <input name="checkbox" id="checkbox_2" type="checkbox" class="custom-control-input" value="fish">
        <label for="checkbox_2" class="custom-control-label">Fish</label>
      </div>
    </div>
  </div>
  <div class="form-group row">
    <div class="offset-4 col-8">
      <button name="submit" type="submit" class="btn btn-primary">Submit</button>
    </div>
  </div>
</form>

app/views/layouts/_menu.html.erb
<nav id='menu'>
  <ul>
    <% if current_user %>
      <li><%= link_to 'Domů', static_home_path %></li>
      <% if current_user.admin? %>
        <li><a class='dropdown-arrow' href='http://'>Admin</a>
          <ul class='sub-menus'>
            <li><%= link_to 'Uživatelé', users_path %></li>
            <li><a href='http://'>Sub Menu 2</a></li>
            <li><a href='http://'>Sub Menu 3</a></li>
            <li><a href='http://'>Sub Menu 4</a></li>
          </ul>
        </li>
      <% end %>
      <% if current_user.manager_or_admin? %>
        <li>
          <a class='dropdown-arrow'>Manažer</a>
          <ul class="sub-menus">
            <li><%= link_to 'Zákazníci', customers_path %></li>
            <li><%= link_to 'Zakázky', orders_path %></li>
          </ul>
        </li>
      <% end %>
      <% if current_user.driver_or_manager_or_admin? %>
        <li>
          <a class='dropdown-arrow'>Řidič</a>
          <ul class="sub-menus">
            <li>dri prvni</li>
          </ul>
        </li>
      <% end %>
      <li><%= link_to "Uprav profil", edit_user_path(current_user.id) %></li>
      <li><%= link_to "Odhlásit", :logout, method: :post %></li>
    <% else %>
      <li><%= link_to "Přihlásit", :login %></li>
    <% end %>
    <li><%= link_to 'O nás', static_about_path %></li>
    <li><%= link_to 'Kontakt', static_contact_path %></li>
    <% if current_user&.admin? %>
      <div id="current_users"> Aktivní uživatelé: <%= current_users_list %></div>
    <% end %>
  </ul>
</nav>

app/views/layouts/_sidebar.html.erb
<!-- Sidebar -->
<div id="sidebar">

  <div class="inner">

    <!-- Menu -->
    <nav id="menu">
      <ul>
        <% if current_user %>
          <li><%= link_to 'Domů', static_home_path %></li>
          <% if current_user.admin? %>
            <li><%= link_to 'A - Uživatelé', users_path %></li>
          <% end %>
          <% if current_user.manager_or_admin? %>
            <li><strong><%= link_to 'Zákazníci', customers_path %></strong></li>
            <li><strong><%= link_to 'Aktivní zakázky', orders_path(scope: 'active') %></strong></li>
            <li><strong><%= link_to 'Ukončené zakázky', orders_path(scope: 'finished') %></strong></li>
            <li><strong><%= link_to 'Faktury', invoices_path(scope: 'not_paid') %></strong></li>
            <li><strong><%= link_to 'Faktury - zaplacené', invoices_path(scope: 'paid') %></strong></li>
            <li><strong><%= link_to 'Auta', cars_path %></strong></li>
            <hr/>
          <% end %>
          <% if current_user.driver_or_manager_or_admin? %>
<!--            <li>dri prvni</li>-->
          <% end %>
          <li><%= link_to "Uprav profil", edit_user_path(current_user.id) %></li>
          <li><%= link_to "Odhlásit", :logout, method: :post %></li>
        <% else %>
          <li><%= link_to "Přihlásit", :login %></li>
        <% end %>
        <li><%= link_to 'O nás', static_about_path %></li>
        <li><%= link_to 'Kontakt', static_contact_path %></li>
<!--        <li>-->
<!--          <span class="opener">Dropdown Two</span>-->
<!--          <ul>-->
<!--            <li><a href="#">Sub Menu #1</a></li>-->
<!--            <li><a href="#">Sub Menu #2</a></li>-->
<!--            <li><a href="#">Sub Menu #3</a></li>-->
<!--          </ul>-->
<!--        </li>-->
      </ul>
    </nav>

    <!-- Footer -->
    <footer id="footer">
      <% if current_user&.admin? %>
        <p id="current_users"> Aktivní uživatelé: <%= current_users_list %></p>
      <% end %>
      <p class="copyright">Copyright &copy; 2021 JH Trans</p>
<!--      <p class="text-center">Aktualizováno: <%#= `git log -1 --format=%cd`.to_datetime.strftime("%d.%m.%Y&nbsp;%T").html_safe %></p>-->
<!--        <br>Designed by <a rel="nofollow" href="https://www.facebook.com/templatemo">Template Mo</a></p>-->
    </footer>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "JH Trans" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield(:head) %>
  </head>

  <body class="is-preload">
    <!-- Wrapper -->
    <div id="wrapper">
      <!-- Main -->
      <div id="main">
        <div class="inner">
          <!-- Header -->
          <header id="header">
            <div class="logo">
              <%= link_to "JH Trans", root_path %>
            </div>
          </header>

          <section class="simple-post">
            <div class="container-fluid">
              <div class="row">
                <div class="col-lg-12">
                  <div class="down-content">
                    <%= yield %>
                  </div>
                </div>
              </div>
            </div>
          </section>

        </div>
      </div>

      <%= render 'layouts/sidebar' %>

    </div>
  </body>
  </html>

app/views/layouts/pdf_contract.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Styles -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <style type="text/css">
        <!--
        /* Font Definitions */
        @font-face
        {font-family:SimSun;
            panose-1:2 1 6 0 3 1 1 1 1 1;}
        @font-face
        {font-family:Mangal;
            panose-1:0 0 4 0 0 0 0 0 0 0;}
        @font-face
        {font-family:"Cambria Math";
            panose-1:2 4 5 3 5 4 6 3 2 4;}
        @font-face
        {font-family:"\@SimSun";
            panose-1:2 1 6 0 3 1 1 1 1 1;}
        /* Style Definitions */
        p.MsoNormal, li.MsoNormal, div.MsoNormal
        {margin:0cm;
            margin-bottom:.0001pt;
            text-autospace:ideograph-other;
            font-size:12.0pt;
            font-family:"Times New Roman",serif;}
        a:link, span.MsoHyperlink
        {color:#0563C1;
            text-decoration:underline;}
        a:visited, span.MsoHyperlinkFollowed
        {color:#954F72;
            text-decoration:underline;}
        p
        {margin-right:0cm;
            margin-left:0cm;
            font-size:12.0pt;
            font-family:"Times New Roman",serif;}
        pre
        {mso-style-link:"Formátovaný v HTML Char";
            margin:0cm;
            margin-bottom:.0001pt;
            font-size:10.0pt;
            font-family:"Courier New";}
        p.Standard, li.Standard, div.Standard
        {mso-style-name:Standard;
            margin:0cm;
            margin-bottom:.0001pt;
            text-autospace:ideograph-other;
            font-size:12.0pt;
            font-family:"Times New Roman",serif;}
        p.-wm-western, li.-wm-western, div.-wm-western
        {mso-style-name:-wm-western;
            margin-right:0cm;
            margin-left:0cm;
            font-size:12.0pt;
            font-family:"Times New Roman",serif;}
        p.-wm-msonormal, li.-wm-msonormal, div.-wm-msonormal
        {mso-style-name:-wm-msonormal;
            margin-right:0cm;
            margin-left:0cm;
            font-size:12.0pt;
            font-family:"Times New Roman",serif;}
        span.FormtovanvHTMLChar
        {mso-style-name:"Formátovaný v HTML Char";
            mso-style-link:"Formátovaný v HTML";
            font-family:"Courier New";}
        .MsoChpDefault
        {font-family:"Calibri",sans-serif;}
        .MsoPapDefault
        {margin-bottom:8.0pt;
            line-height:107%;}
        @page WordSection1
        {size:595.3pt 841.9pt;
            margin:70.85pt 70.85pt 70.85pt 70.85pt;}
        div.WordSection1
        {page:WordSection1;}
        -->
    </style>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf_invoice.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Styles -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <style type="text/css">
        .line {
            border-bottom: 3px solid #000;
            width: 100%;
        }

        .line-light {
            width: 100%;
            border-bottom: 1px solid #949597;
        }

        .line-end {
            width: 100%;
            border-bottom: 3px solid #f0c29e;
        }

        .data {
            background-color: #dcdddf;
            padding-left: 45px;
        }

        .data .data-box {
            margin-top: 60px;
        }

        .data .data-box .data-separator {
            border-top: 1px solid #949597;
            width: 10%;
        }

        .content {
            background-color: #f1f1f1;
            padding-right: 45px;
        }

        .without-margin {
            margin: 0 !important;
        }

        /* To break in pages, please use this class */
        /* https://github.com/barryvdh/laravel-snappy/issues/2 */
        .page
        {
            page-break-after: always;
            page-break-inside: avoid;
        }

        .tg {
            border-collapse: collapse;
            border-spacing: 0;
            width: 900px;
            /*margin: 40px;*/
            margin-top: 10px;
            margin-left: 40px;
        }

        .tg td {
            border-color: black;
            border-style: solid;
            border-width: 1px;
            font-family: Arial, sans-serif;
            font-size: 20px;
            overflow: hidden;
            padding: 10px 5px;
            word-break: normal;
            width: 75px;
        }

        .tg th {
            border-color: black;
            border-style: solid;
            border-width: 1px;
            font-family: Arial, sans-serif;
            font-size: 20px;
            font-weight: normal;
            overflow: hidden;
            padding: 10px 5px;
            word-break: normal;
        }

        .tg .tg-zv4m {
            border-color: #ffffff;
            text-align: left;
            vertical-align: top
        }

        .tg .tg-8jgo {
            border-color: #ffffff;
            text-align: center;
            vertical-align: top
        }

        .tg .tg-3z1b {
            border-color: #000000;
            text-align: right;
            vertical-align: top
        }

        .tg .tg-h25s {
            border-color: #ffffff;
            font-weight: bold;
            text-align: right;
            vertical-align: top
        }

        .tg .tg-ofj5 {
            border-color: #ffffff;
            text-align: right;
            vertical-align: top
        }

        .tg .tg-73oq {
            border-color: #000000;
            text-align: left;
            vertical-align: top
        }

        .velikost_18 {
            font-size: 18px;
            padding: 0;
            margin: 0;
        }

        .velikost_15 {
            font-size: 15px;
        }

        .tucne {
            font-weight: bold;
        }
    </style>
  </head>
  <body>
    <%= yield %>
  </body>
</html>